### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by hitchcott** [orionjs/core#10]
Hi @nicolaslopezj,

I have enjoyed testing orion and wondered if you have plans to implement routing that is not declared within the code of the app? I.e. the ability to create and remove pages via the admin panel.

Thanks!

**Comment by iamkevingreen** [comment]
@hitchcott The way I've been doing it is creating basic routes in the code but then adding an additional field to my collection like `slug`. But possibly adding like menu control or something would be cool too. 

Is that sort of what you were getting at? But basically create a pages collection and add something like slug and then you can navigate to it at the root level of your app like how wordpress handles it. 

localhost/contact
localhost/about

```
  // General Pages
  this.route('page', {
    path: ':slug',
    layoutTemplate: 'layout',
    fastRender: true,
    waitOn: function() {
      return [orion.subs.subscribe('entity', 'pages', {slug: this.params.slug})];
    },
    data: function() {
      page = orion.entities.pages.collection.findOne({slug: this.params.slug});
      var response = this.response;
      console.log(response);
      if (page === undefined) {
        // this.redirect('base');
        return null;
      }
      return orion.entities.pages.collection.findOne({slug: this.params.slug});
    },
    onAfterAction: function() {
      post = orion.entities.pages.collection.findOne({slug: this.params.slug});
      dict = orion.dictionary.collection.findOne();
      title = page.title + ' | ' + dict.seoTitle;
      SEO.set({
        title: title,
      });
      GAnalytics.pageview();
    }
  });
```

**Comment by nicolaslopezj** [comment]
I will create a package. I don't think it's a good idea to include it to the core. 
Any ideas before starting to work on this will be very appreciated.

**Comment by hitchcott** [comment]
@iamkevingreen, Exactly, yes -- how you describe it. Thanks for that gist; seems like it covers the basics

@nicolaslopezj I agree it shouldn't be in core -- just wasn't sure where else I should have made this issue. 

Thanks for offering to making a package; I think it would be a great next feature. Quite a few potential things to consider I suppose:

* Some way of defining multiple dictionaries/entities per route, with ordering + layout options
* Menu population
* Route-based layouts
* Other root config

Not that they are all needed to get something worth while.

Anyway, I'm hoping to get some free time at some point to take a deeper look at orion.

**Comment by semikolon** [comment]
+1

**Comment by nicolaslopezj** [comment]
https://github.com/orionjs/pages

**Comment by semikolon** [comment]
Cool.
tis 17 mar 2015 kl. 03:58 skrev Nicolás López <notifications@github.com>:
