### ISSUE TITLE
Entity index table structure does not change when navigating between different entities

### ISSUE THREAD

**Issue by desertjinn** [orionjs/core#11]
I have a few entities defined and each has its own individual structure for its index table.
This is an entity named 'sports' - 
![screenshot from 2015-01-16 20 09 32](https://cloud.githubusercontent.com/assets/9519467/5777772/9f0e9bc2-9dbb-11e4-9663-48d67d01ff2f.png)

This is another entity named 'events' -
![screenshot from 2015-01-16 20 10 07](https://cloud.githubusercontent.com/assets/9519467/5777800/c6889022-9dbb-11e4-8671-a92fe87f2b88.png)

If I select 'sports' first and then switch to 'events' the index table ends up looking like this -
![screenshot from 2015-01-16 20 12 27](https://cloud.githubusercontent.com/assets/9519467/5777846/38c8cbac-9dbc-11e4-829c-1fbd17571a94.png)

No console error messages are shown.
![screenshot from 2015-01-16 20 15 18](https://cloud.githubusercontent.com/assets/9519467/5777891/7feafc3a-9dbc-11e4-9333-d0d20b3941b3.png)

This only happens when navigating between entities. 
Any idea why?

**Comment by nicolaslopezj** [comment]
Maybe it's an issue with autopublish. Can you try updating all dependencies and removing autopublish before dig in into this problem

**Comment by desertjinn** [comment]
I have updated the dependencies and removed autopublish but index table structure is still behaving the same. The table structure of the first entity selected seems to persist while navigating between other entities.

**Comment by nicolaslopezj** [comment]
Ok. I will fix this tonight

**Comment by nicolaslopezj** [comment]
Sorry, ```aldeed:tabular``` is too buggy. I'm thinking in changing it.

**Comment by desertjinn** [comment]
Hope you find something suitable soon, your package is truly an awesome addition to meteor.

**Comment by nicolaslopezj** [comment]
Didn't fix ```aldeed:tabular``` but I did a trick to make it work.
PD: ```aldeed:tabular``` it's not entirely buggy, but in the tracker topic yes it is

**Comment by desertjinn** [comment]
So updating the package will fix it ?

**Comment by desertjinn** [comment]
Updated the package, the edit/delete buttons are gone from the table but I am able to edit and delete by selecting the table element :+1: . Nice fix.

New issue : 
I had a select option specified with options and value and am using the format 

```javascript
{value:'labelvalue',label:'labelname'} 
```
and this worked before the update. After updating, no values are available for the select box.
![screenshot from 2015-01-20 20 01 49](https://cloud.githubusercontent.com/assets/9519467/5818925/7f14e17e-a0df-11e4-9534-a9376f456185.png)

**Comment by nicolaslopezj** [comment]
Sorry, I was using the submit button the wrong way.

**Comment by desertjinn** [comment]
It works!! :+1: 

P.S - I have a doubt.
When setting up select box, supplying values in the format **{value:'labelvalue',label:'labelname'}**, everything works perfectly. :+1: 

But I am setting the select box options by calling **function getVenues()** and returning all the values in the prescribed format. This just shows an empty select box now. This used to work fine before the update to 0.4.6.

```javascript
function getVenues() {
	var venues = orion.entities.venues.collection.find().fetch();
	var venuesmin = [];
	_.each(venues,function(item){
		venuesmin.push({value:item._id,label:""+item.title+""});
	});
	if(venuesmin)
		return venuesmin;
	return [];
}
```

I configured the select box like this -
```javascript
orion.addEntity('sports', {
	title: {
		type: String,
		label: "Sport Title",
	},
	venue: {
		type: String,
		label: "Venue",
		optional: true,
		autoform: {
            type: 'select',
            options :getVenues(),
        }
	},
	
},  {
	icon: 'cubes',
	sidebarName: 'Sports',
	pluralName: 'Sports',
	singularName: 'Sport',
	
	tableColumns: [
		{ data:'title', title: 'Sport' },
		{ 
			data:'venue', 
			title: 'Venue', 
			render: function(val, type, doc) {
				var venuename = orion.entities.venues.collection.findOne({_id:doc.venue},{fields:{title:1}});
				if(venuename) return venuename.title;				
			}, 
		},
	]
});
```

Specifically retrieving the *venues* entity collection gives me an empty array.
```javascript
var venues = orion.entities.venues.collection.find().fetch();
console.log(venues)  //=> Array[0]
```

Any ideas as to what I'm messing up?

**Comment by nicolaslopezj** [comment]
It's because you are not subscribed. 
Add this line of code in the client

	orion.admin.addAdminSubscription(orion.subs.subscribe('entity', 'venues'));

**Comment by desertjinn** [comment]
Yes, that worked. I also had to tweak calling the function to populate options like this
```javascript
autoform: {
            type: 'select',
            options : function(){
            	var venues = orion.entities.venues.collection.find().fetch();
				var venuesmin = [];
				_.each(venues,function(item){
					venuesmin.push({value:item._id,label:item.title});
				});

				if(venuesmin)
					return venuesmin;
				return [];
            },
        }
```

prior to v0.4.6 I got the values by calling a function defined outside the entity.
