### ISSUE TITLE
404 at /admin and conflict with onCreateUser function

### ISSUE THREAD

**Issue by buduguru** [orionjs/core#13]
1. When I first added `orionjs:core` and `orionjs:styles` to my app that I already developed, it did not crush but /admin was unavailable (error 404). Then I tried to install orion on a fresh app and it worked OK. I noticed that more dependencies were installed that time. Then I ran `meteor update` on the 1st app and indeed it added some dependencies that were not added before. 

2. Ok, I ran meteor and there was an error `can only call onCreateUser once`. I used `onCreateUser` function to add some additional fields inside users' profile field. So, I commented the function out , ran meteor again, the app opened OK and /admin was accessible.  

So, all is solved except inability of `onCreateUser` usage. Maybe I can add new fields to users from the orion config? I did not find any clue in http://orion.meteor.com/docs/accounts . Should I add new fields by means of `useraccounts-core` package?(it was added as one of dependencies)

**Comment by nicolaslopezj** [comment]
To edit some fields of the users you can create a custom section on the admin.
```js
orion.admin.addSidebarTab({
    routeName: 'adminAccountsEditFields',
    navbarTitle: 'Edit Fields',
    activeRouteRegex: 'adminAccountsEditFields',
    icon: 'users',
    permission: 'admin'
});
```
You have to create the route with iron router with that same name. If the connected user is an admin, it will already be subscribed to the users collection.
Create a Meteor method that edit the fields you want and call it from the template.

**Comment by buduguru** [comment]
Thank you. I will try it.

**Comment by buduguru** [comment]
I found how to do that in useraccounts. All custom fields indicated in sign up form are automatically added to Meteor.user().profile after account creation. In my case I just need to make them hidden like this:

```javascript
AccountsTemplates.addFields([
    {
        _id: 'ratedItems',
        type: 'hidden'
    },
    {
        _id: 'starredItems',
        type: 'hidden'
    }
]);
```

**Comment by splendido** [comment]
perhaps providing a hook to let the dev further modify the user object on creation would be a good idea?

something like:

```javascript
Accounts.onCreateUser(function (options, user) {
	user.permissions = orion.users.permissions.defaultPermissions;
	user.profile = options.profile;
	user.registrationType = options.registrationType || 'register';
	if (orion.onCreateUser) {
		user = orion.onCreateUser(user);
	}
	return user;
});
```

it's a shame that the usage of `Accounts.onCreateUser` is prohibited to the developer ;-)
