### ISSUE TITLE
useraccounts:bootstrap vs useraccounts:semantic-ui

### ISSUE THREAD

**Issue by buduguru** [orionjs/core#14]
Orion.js depends on useraccounts:bootstrap but I use semantic-ui on frontend and thus would like to use useraccounts:semantic-ui for users to sign up/in. When I add the latter, it conflicts with the bootstrap version. How can I solve it without forking Orion.js and making new package?

**Comment by nicolaslopezj** [comment]
Sorry, you can't do that without forking. Maybe you can fork, make it optional and do a pull request. 
But bootstrap is already loaded with Orion, so it's not necessary to change the login to semantic-ui

**Comment by buduguru** [comment]
Yes, I understand that if I need all the styles to be consistent I need to rewrite admin html to semantic-ui too. But for now it is only important to have useraccounts forms styled with semantic-ui on non-admin pages. Thank you.
