### ISSUE TITLE
Using OrionJS with existing app that already has a router.

### ISSUE THREAD

**Issue by silentwarrior** [orionjs/core#15]
Hello.

I am trying this out for my app, my app already has a router and routes configured, so, /admin will fail everytime.

How can I add this properly without messing up the existing app or the admin part?

**Comment by nicolaslopezj** [comment]
I really don't know why this is happening to everyone. Try going to .meteor/packages and put Orion right after meteor-platform

**Comment by silentwarrior** [comment]
This is my packages file as you can see, orion is last :

# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
mike:mocha
iron:router
dburles:collection-helpers
matb33:collection-hooks
aldeed:collection2
accounts-password
aldeed:tabular
aldeed:template-extension
alanning:roles
meteorhacks:unblock
orionjs:core
orionjs:styles

**Comment by buduguru** [comment]
Look at this issue https://github.com/orionjs/core/issues/13. 
`meteor update` worked for me.

**Comment by silentwarrior** [comment]
When I did meteor update, the project broke for me. I had to comment out all orion lines in packages file.

Error : http://inft.ly/3466bWR

After commenting out both orionjs lines : http://inft.ly/8vzNbuZ

Does this make any sense to you?

**Comment by nicolaslopezj** [comment]
Please use version 0.4.2 until I fix the issue with tabular
orion:core@=0.4.2

**Comment by silentwarrior** [comment]
http://meteorpad.com/pad/miaWhJ7yYpry4STyY/Leaderboard shows me no error, and thats strange.

Replacing :
#aldeed:tabular
nicolaslopezj:tabular

Now gives me another error for "/login" already exists, I assume this is a step forward. Will replace the routes names and see if I get closer to a solution.

**Comment by silentwarrior** [comment]
Using v0.4.2, it errors out if I use nicolaslopezj:tabular and not aldeed:tabular, so its flipped.

v0.4.2 => aldeed:tabular
v0.4.3 => nicolaslopezj:tabular

**Comment by nicolaslopezj** [comment]
Remove iron:router from you dependencies and put Orion right after meteor-platform

**Comment by silentwarrior** [comment]
With that change and putting 0.4.3 as the version number:
meteor update : http://puu.sh/eE83n/1f5583b6ea.png

Fail : http://puu.sh/eE877/a6d286e288.png

**Comment by silentwarrior** [comment]
meteor-platform
orionjs:core
orionjs:styles
mike:mocha
-#iron:router
dburles:collection-helpers
matb33:collection-hooks
aldeed:collection2
accounts-password
aldeed:tabular
-#nicolaslopezj:tabular
aldeed:template-extension
alanning:roles
meteorhacks:unblock

**Comment by nicolaslopezj** [comment]
Use version 0.4.2 until 0.4.4 is out please

**Comment by silentwarrior** [comment]
Alright will do.

Regarding the sorry not allowed here after admin registration, what should I do ?
http://puu.sh/eGp0n/05bbcc3223.png

**Comment by nicolaslopezj** [comment]
That is happening because the method you use to create the user was no the official. You can edit the use via ```mongo shell```.
Users must have this attributes:
```js
{
   isAdmin: true,
   permissions: ['files.folders', 'files.upload', 'dictionary.basic'] // if its a admin leave it blank
}
```

**Comment by nicolaslopezj** [comment]
That is happening because the user doesn't have

**Comment by nicolaslopezj** [comment]
I think this should be closed. You can still ask questions here
