### ISSUE TITLE
Setup Orion for editing the users collection, causes fail.

### ISSUE THREAD

**Issue by silentwarrior** [orionjs/core#16]
Hello.

I am trying to setup orion for the users collection, that is a special case if meteor.users exists (accounts package).

Since the AddEntity will internally do Meteor.Collection (and new SimpleSchema), the "error '/users/insert' is already defined" will show up.

It should check if the collection is "users", and if so, use Meteor.users instead of new Mongo.Collection like I do in my app:
```
            var col;
            if(collectionName === "users")
                col = TSW.Collections[collectionName] = Meteor.users;
            else
                col = TSW.Collections[collectionName] = new Mongo.Collection(collectionName);
```

If we use SimpleSchema on our app, it will also cause problems since orion also creates a new SimpleSchema object.

I can for example compromise my design to receive a SimpleSchema object from orion.addEntity, in that case, I can then check, hey do we have an orionOptions object? if so, then addEntity and use the return for our SimpleSchema, if not then just create a new SimpleSchema.

PS: For completeness, here is the code I am using : http://pastebin.com/dFk5nCvj
PS2: Using Mongo.Collection because the docs state it should now be used like that, is suspect Meteor.Collection will be depreciated soon.

**Comment by nicolaslopezj** [comment]
I think its best to leave the entities like that and add some apis to make more things with the users in the admin

**Comment by nicolaslopezj** [comment]
[User Actions](http://orion.meteor.com/docs/extending)

**Comment by codeHatcher** [comment]
I'm in a similar situation but the docs you have linked no longer exist.
