### ISSUE TITLE
No 'create' button in Users tab.

### ISSUE THREAD

**Issue by alex-wilmer** [orionjs/core#18]
According to the docs I should be able to create new users through the UI. I don't see this option anywhere.

**Comment by nicolaslopezj** [comment]
You can create invitations and use that invitations to create new users

**Comment by alex-wilmer** [comment]
How do I create invitations? All I see is this http://i.imgur.com/WQkwoUW.png

**Comment by nicolaslopezj** [comment]
You have issues with the css. The button should be there

**Comment by alex-wilmer** [comment]
Ok sorry found my mistake

    @media only screen and (min-width: 600px)
      .title 
        display: none;
