### ISSUE TITLE
Enhancement: Move views out of core

### ISSUE THREAD

**Issue by kevohagan** [orionjs/core#26]
This is a very promising suite of packages, and i definitely agree with you that the dictionary has huge value as a CMS.

I am setting up a project with orionjs and i found myself cloning both core and styles locally to modify a bit the look and feel.

What are your thoughts on moving views out of core and just have the core package with funcitonality (similar to useraccounts:core) and then have orionjs:bootstrap, orionjs:semantic, orionjs:polymer etc etc

**Comment by nicolaslopezj** [comment]
I think this is really necessary. It's a lot of work, but it will make orion more open and flexible

**Comment by iamkevingreen** [comment]
Yeah I was doing the same thing, even with my orion-sass-styles admin stuff. I'd love to just class and structure the admin my own way without having to pull it out of the core when I do it. 

+1

**Comment by loongmxbt** [comment]
How to customize admin template based on orionjs:bootstrap.

I mean I want to redefine `<template name="adminLayout"> </template>` at views/admin/base.html , and let it override the package's base.html, how can I do that?

**Comment by nicolaslopezj** [comment]
You can download the bootstrap repository and put it in your app's /packages folder, you can edit it however you want
