### ISSUE TITLE
Add jade support

### ISSUE THREAD

**Issue by timfam** [orionjs/core#27]
Please add 'mquandalle:jade', to api.use

**Comment by nicolaslopezj** [comment]
Why is this necessary? Why is not possible to add it to the app packages?

**Comment by timfam** [comment]
Hi Nick,
I cloned core because I need to use autoForm instead of  quickForm in the admin/views/entities/* . With out adding jade to api.use it won't compile. I think enough people use jade that adding support for it will be great.

**Comment by nicolaslopezj** [comment]
Can you try to make it work with the new update (views out of the core)?

**Comment by timfam** [comment]
You are  the best, I suppose, views in now packages as Bootstrap?

**Comment by nicolaslopezj** [comment]
@timfam Yes

**Comment by timfam** [comment]
Works, but I am still going to have to clone bootsrap, I guess that is better than cloning core. Meteor don't yet have a way of over-riding packages  from other packages or files. I.e in drupal, page-20.tpl.php overrides page.tpl.php

**Comment by nicolaslopezj** [comment]
Well, the purpose of moving the views out of the core is that anyone can easily edit the admin templates. I think cloning bootstrap is a great solution

**Comment by timfam** [comment]
Cloning is good enough for now but bad idea in the long run. Packages should never be directly edited, we need a mechanism for over-riding files. I want to keep benefiting from updates to bootsrap rather than branch off. What I saying is bootstrap should be treated as an extended admin theme, make sense?

**Comment by nicolaslopezj** [comment]
Orion is made to support multiples views packages, you can fork and fetch updates. All the logic of the templates is still in the core (look [here](https://github.com/orionjs/core/tree/master/admin/client-common) and [here](https://github.com/orionjs/bootstrap/blob/master/views/common.js)).

Maybe we can have another solution, what are you trying to do?

**Comment by timfam** [comment]
Yes I see that. I have looked across meteor nothing comes close t orionjs and going forward this will be the defacto admin theme; the community just don't know it yet. Orionjs can be the theme that introduces true extensibility. right now I am forced to clone the whole bootrap - bad. I am only interested in overiding a few files. This will be great if we can first do a check for  local package called orion:bootstrapLocal and if  "entities.html" exist use it.  
This way only edge cases are handle with bootstrapLocal

**Comment by nicolaslopezj** [comment]
Maybe you can use this package to override few templates https://github.com/aldeed/meteor-template-extension#replacestemplatename

**Comment by timfam** [comment]
Helpful but not quite there. You have done a great job and I know it's been a long day for you. We can approach this issue with fresh eyes tomorrow or perhaps others will contribute to this discussion, Maybe I should bring it up in meteor forum. Meteor just has to have a standard way of over riding packages. I will spend more time looking at above link to see what truth can be found there :)

**Comment by nicolaslopezj** [comment]
How is this going?

**Comment by timfam** [comment]
Hi @nicolaslopezj,
I added support for jade and used autoform for more flexibility(toggle field display). This is why I could not contribute it back 
```
.admin-top-nav
  span.title Create a new #{ entity.options.singularName }
.admin-content
    //- use autoform to enable toggling field display based on value of parent field 
    //-http://autoform.meteor.com/fieldvalues
  +autoForm collection=entity.collection id="createEntityForm" \
  type="insert" template="bootstrap3-horizontal" label-class="col-sm-3" \
  input-col-class="col-lg-7 col-md-8 col-sm-9 input-container"
    +afQuickField name='section' options="allowed"
    +if(afFieldValueIs name="section" value="ABC")
      +afQuickField name='abc' options="allowed"
      +afQuickField name='title'
      +afQuickField name='body'
    +if(afFieldValueIs name="section" value="Availability")
      //-styling the subfields here
      #Availability-form
        +afQuickField name='field1'
        +afQuickField name='field2'
        +afQuickField name='field3'
        +afQuickField name='field4'
    +afQuickField name='image' id='image'
    .form-group
      button.btn.btn-primary(type='submit') Add Content
      button.btn.btn-default(type='reset') Reset Form

```

**Comment by nicolaslopezj** [comment]
Ok. But is this problem solved?

**Comment by timfam** [comment]
Yes I will open an another enhancement ticket later.
