### ISSUE TITLE
After a meteor update, admin area error

### ISSUE THREAD

**Issue by rdewolff** [orionjs/core#30]
Hi all

I just did a ```meteor update``` and tried to reach the admin panel. The following arise when I open mywebsite/admin :

```
Couldn't find a template named "adminAccountsLogin" or "adminAccountsLogin". Are you sure you defined it?
```

Any idea what went wrong?

**Comment by joadr** [comment]
rdewolff
Views were moved out of the orionjs:core in order to give suppor to other technologies different from bootstrap.
To solve your issue just install orionjs:bootstrap like this:
meteor add orionjs:bootstrap

**Comment by rdewolff** [comment]
Thanks for your answer. Added the ```orionjs:bootstrap``` package did the trick. Now everything works like a charm! 
Thanks!

**Comment by nicolaslopezj** [comment]
Great!
