### ISSUE TITLE
Realtionships

### ISSUE THREAD

**Issue by rdewolff** [orionjs/core#33]
Is there a plan to enable relationships with Entities? Like having 1-1, 1-N and N-N relationships between them?

That'd be a very nice step ahead and be very helpful to build more complex data structure.

**Comment by nicolaslopezj** [comment]
I've always have had the idea of enable relations, but I have always managed to make hacky things to not use them (and I think everyone).
I knew adding thing would be necessary in some time. 
I will add this in the to-do list

**Comment by nicolaslopezj** [comment]
https://trello.com/b/dQhi5dF9/orion-roadmap

**Comment by rwatts3** [comment]
I second this . I am coming from the yogiben-meteor-admin platform , and the ability to tie relationships such as posts to comments or posts to users was a feature that I used pretty heavily.

**Comment by nicolaslopezj** [comment]
https://github.com/orionjs/relationships

**Comment by rdewolff** [comment]
Amazing!
