### ISSUE TITLE
Improve documentation site

### ISSUE THREAD

**Issue by nicolaslopezj** [orionjs/core#34]
What do you think about the current documentation site?
Would you prefer that the docs is on orion.meteor.com or github?

**Comment by iamkevingreen** [comment]
I think you're actually doing a pretty good job with the docs, totally fine if they live somewhere else, whatever is easier for you to update is the one you should use. :+1:

**Comment by nicolaslopezj** [comment]
I changed the documentation to github, becouse its easier to edit and its better to have all in one place

**Comment by kevohagan** [comment]
Yes i agree, github is the primary place to look at! :)

**Comment by nicolaslopezj** [comment]
Documentation is back on the site. It's integrated with Github
