### ISSUE TITLE
orion web site down?

### ISSUE THREAD

**Issue by rdewolff** [orionjs/core#35]
Hi all

Just tried to reach the web site (for example http://orion.meteor.com/docs/attributes) but it's not working.

Can you check this please?

Cheers

**Comment by kevohagan** [comment]
as nicolas said, he is deprecating the orion.meteor.com website for docs on
github : easier to maintain and contribute. So better just go here to read
about attributes :
https://github.com/orionjs/core/tree/master/attributes

**Comment by rdewolff** [comment]
Thanks, didn't know he was deprecating orion.meteor.com!

Cheers

**Comment by nicolaslopezj** [comment]
Documentation is back on the site. It's integrated with Github
