### ISSUE TITLE
Orion entities relationships via autoform afFieldInput multiple (select)

### ISSUE THREAD

**Issue by rdewolff** [orionjs/core#36]
Hi all

Am trying to link 2 entities together via it's ID, via a 1-N (one to many) relationship (should be simple).

So I have ```pages1``` and ```pages2```, and I want page1 to have many ```page2``` linked. So I put in ```page2``` a field ```parent``` and use a ```select``` (via autoform) to link it. 

Problem: cannot make it work. First the type of object wasn't accepted. Now this code is the closest I can get, but my meteor app doesn't update/save anything and there are no error message.

Here is the pages1.js and pages2.js entities declaration files :

page1.js
```js
// 1st level pages
orion.addEntity('pages1', {
    title: {
        type: String,
        label: "Titre"
    },
    content: orion.attribute('froala', {
        label: "Contenu"
    })
}, {
    icon: 'bookmark',
    sidebarName: 'Page niveau 1',
    pluralName: 'Pages1',
    singularName: 'Page1',
    tableColumns: [
        { data:'title', title: 'Titre' },
        { data:'content', title: 'Contenu' }
    ]
});
```
page2.js
```js
// 2nd level pages
orion.addEntity('pages2', {
    title: {
      type: String,
      label: "Titre"
    },
    content: orion.attribute('froala', {
      label: "Contenu"
    }),
    image: orion.attribute('file', {
      label: 'Image',
      optional: true
    }),
    liens: {
      type: [String],
      label: "Liens",
      optional: true
    },
    articles: orion.attribute('file', {
      label: 'Article',
      optional: true
    }),
    parent: {
      type: [Object],
      autoform: {
        // type: "select2", // FIXME: specifying SELECT2 type makes an error
        afFieldInput: {
          multiple: true
        },
        options : function() {
          return orion.entities.pages1.collection.find().map(function (obj)  {
            return {
              label: obj.title,
              value: obj._id
            };
          });
        },
      },
      label: 'Parent',
      optional: true
    }
}, {
    icon: 'bookmark',
    sidebarName: 'Page niveau 2',
    pluralName: 'Pages2',
    singularName: 'Page2',
    tableColumns: [
        { data:'title', title: 'Titre' },
        { data:'content', title: 'Contenu' }
    ]
});
```

Do you have any idea why this ain't working? Maybe a better way to make relationships like this work?

Thanks in advance for your help and advice!

Cheers

**Comment by nicolaslopezj** [comment]
A better way to do this it's coming, but in the meantime:
Are you subscribed to page1 on the page2 form? Check this https://github.com/orionjs/core/blob/master/api

**Comment by rdewolff** [comment]
Lemme check this

**Comment by rdewolff** [comment]
What are the arguments you use there, in the doc you write :

```The arguments are the same arguments of the original subscription.```

Which is not really clear. Tried :

```js
orion.admin.addAdminSubscription('pages1');
orion.admin.addAdminSubscription('entity', 'pages1');
```

but both generate errors.

**Comment by rdewolff** [comment]
After meteor full restart, the ```orion.admin.addAdminSubscription('entity', 'pages1');``` seems to be accepted. 
But that doesn't resolve my problem. 

Do you have any example to share where you implement this?

**Comment by nicolaslopezj** [comment]
The second should work. What error is showing?

**Comment by rdewolff** [comment]
As just written, the second works. But the problem in the admin is not resolved : cannot submit or save the page2 entity!

**Comment by nicolaslopezj** [comment]
What it's not working? Please be more specific

**Comment by rdewolff** [comment]
When I go create or edit the page2 entity, clicking on the "Submit" (create) or "Save" (edit) button has no action. No error displayed in console.

**Comment by rdewolff** [comment]
Have you been able to reproduce the problem @nicolaslopezj ?

**Comment by nicolaslopezj** [comment]
I'm on it

**Comment by nicolaslopezj** [comment]
You must change ```Object``` to ```String```

```js
parent: {
      type: [String],
```

**Comment by rdewolff** [comment]
Will try this now

**Comment by rdewolff** [comment]
Yes! This works now! Thanks @nicolaslopezj !

**Comment by rwatts3** [comment]
If I need to subscribe , where do you add the subscription ? 
Is it within the entity ?

**Comment by nicolaslopezj** [comment]
As a temporary solution, you can subscribe in all the admin. https://github.com/orionjs/core/tree/master/api#subscriptions
