### ISSUE TITLE
Issue using admin panel after update to 0.5.5.

### ISSUE THREAD

**Issue by aaronlake** [orionjs/core#38]
Recently updated to orionjs:core and Meteor 1.0.4.1, console returning this now:
```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
debug.js:41 Received error from server:  Malformed subscription
debug.js:43 For:  Object {msg: "sub", id: "PBsrZTQZmiyQzD4vm", name: Object, params: Array[0]}id: "PBsrZTQZmiyQzD4vm"msg: "sub"name: Objectparams: Array[0]__proto__: Object
```

**Comment by nicolaslopezj** [comment]
Are you using this function?
```js
orion.admin.addAdminSubscription([arguments])
```

**Comment by aaronlake** [comment]
I am not.

**Comment by nicolaslopezj** [comment]
I'm not having this error. Please specify more

**Comment by aaronlake** [comment]
The site is fairly basic, the only references to Orion are the a number of dictionary.addDefinitions in a dictionary.js:

```js
orion.dictionary.addDefinition("homeRight", "Home Right",
  orion.attribute('froala', {
    label: "Home Right",
    optional: true
  })
);

orion.dictionary.addDefinition("newsLeft", "News Left",
  orion.attribute('froala', {
    label: "News Left",
    optional: true
  })
);
```

And calls to the dictionary (home.html):
```html
    <div class="large-6 columns">
      <p class="note-text">{{{dict 'homeRight'}}}</p>
      <br>
      <div class="text-center"><a href="#" class="button">Buy the Book</a></div>
    </div>
```

**Comment by nicolaslopezj** [comment]
When does the error appears? on the admin?

**Comment by aaronlake** [comment]
Appears in the console after loading the page after browsing to /admin which redirects to /admin/directory. The page has the star background with a spinner, no elements displayed.

**Comment by nicolaslopezj** [comment]
Strange, try to clean the project earsing dependecies. 
Anyone else having this issue?

**Comment by jorisroling** [comment]
I  did, but after removing the entire local meteor store (in **~/.meteor**), it did get away. I remember the orionjs:filesystem was stuck on 0.0.13 (altough I **meteor update**d it more than once). After the cleansing, I got the proper 0.0.15 version, and the above error was gone. Does that help?

**Comment by nicolaslopezj** [comment]
That might be the error because filesystem 0.0.13 is not compatible with orion 0.5.5.

**Comment by aaronlake** [comment]
orionjs:filesystem wasn't installed for some reason. I installed and updated to 0.0.15, works fine now.
