### ISSUE TITLE
How to set Default field value or autoValue.

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#39]
What is the correct way and syntax for setting the default field value or the autoValue of the field ?

**Comment by rwatts3** [comment]
Also are there any updates when we will be able to bind relationships. 
For instance If I have a post entity and a comments entity I would like to bind the comments to the post they were created under. 

I believe yogiben's auxCollection does something similar to this but I am not sure.

**Comment by nicolaslopezj** [comment]
If can do it defining it on the schema (SimpleSchema) you can do it on entities. 
Relationships is not ready yet, but a lot of people has managed to do. Check this for example https://github.com/orionjs/core/issues/36
