### ISSUE TITLE
Documentation on orion.users.configure

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#40]
I am trying to understand the syntax such as entity.posts.personal, entity.posts.? 
Is there documentation on the items that can be passed and the best syntax to use ?

**Comment by nicolaslopezj** [comment]
It's like a pyramid, more dots, more specific.
If a user has the permission ```entity.posts.personal``` when you this will happen:

```js
user.hasPermission('entity') // true
user.hasPermission('entity.posts') // true
user.hasPermission('entity.post') // false
user.hasPermission('entity.posts.personal') // true
user.hasPermission('entity.posts.all') // false
``` 

What items do you want to pass? 
Best syntax in which case?

**Comment by rwatts3** [comment]
nicolaslopezj this is actually what I was looking for I'm just trying to better understand what's available to me when I assign default permissions.

**Comment by nicolaslopezj** [comment]
Help on the documentation is always needed, if you want to help, you can modify the README files. https://github.com/orionjs/core/blob/master/users/README.md

**Comment by rwatts3** [comment]
That sounds like a good deal.  I'd be happy to help.  Will you add me as a collaborator.

**Comment by nicolaslopezj** [comment]
You can edit these files and send pull requests
