### ISSUE TITLE
How to determine if a user isAdmin on the front end ? 

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#42]
In conjunction with a previous issue I submitted I would like to know what is the easiest way to run an if within the template to determine if the user is an admin or has permissions to do something. 

For instance I would like to say 
`
   {{#if isAdmin}} 
    display something that only a user with admin permissions would be able to see, however on the    front end. 
{{/if}}
`

**Comment by nicolaslopezj** [comment]
If the user is an admin, all permissions will return true. This is how it's used in the admin templates
```html
{{# if doIHavePermission 'admin' }}
    <!--admin content here-->
{{/ if }}
```

**Comment by rwatts3** [comment]
Nice , thanks man this will work!
