### ISSUE TITLE
Documentation for creating extensions for Orionjs

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#44]
Is there any documentation or a guide for creating Orionjs extensions, for instances how you created orionjs:pages , orionjs:s3 . etc. 

I would like to start contributing by building extensions. Also are extensions the same thing as orion.attribute ?

**Comment by nicolaslopezj** [comment]
```orionjs:pages``` uses:

- To add the button of the pages section on the admin https://github.com/orionjs/core/tree/master/api#adding-tabs
- To allow the admin to set pages permissions https://github.com/orionjs/core/tree/master/users#register-permissions

```orionjs:s3``` uses:

- To use the filesystem api https://github.com/orionjs/filesystem#creating-a-provider

```orionjs:filesystem``` uses:

- To add the button of the files section on the admin https://github.com/orionjs/core/tree/master/api#adding-tabs
- To make the files collection available all through the admin https://github.com/orionjs/core/tree/master/api#subscriptions
- To allow the admin to set files permissions https://github.com/orionjs/core/tree/master/users#register-permissions

```orionjs:file-attribute``` uses:

- To upload files https://github.com/orionjs/filesystem#uploading-files-through-filesystem
- To be a orion attribute https://github.com/orionjs/core/blob/master/attributes/README.md#creating-orion-attributes

```orionjs:froala-editor``` and ```orionjs:summernote``` uses:

- To be a orion attribute https://github.com/orionjs/core/blob/master/attributes/README.md#creating-orion-attributes

**Comment by nicolaslopezj** [comment]
And you can check the code of each extension if it helps. Also, if you think you can make the documentation better, please make a pull request.

**Comment by rwatts3** [comment]
Thank you @nicolaslopezj . I will look into the filesystem issue here #8  . and see if I can make this an extension of some sort.
