### ISSUE TITLE
Create Home link in the admin area.

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#45]
Similar to how you've done the `Logout` button. I believe it would be efficient for a `Home` or `Site` button to be created in the admin section. Once clicked it will take you to the home page of the site so the user doesn't always have to remove \admin\ from the url to get to the home page. 

Any ideas on the best way to implement this?

**Comment by rwatts3** [comment]
I was able to successfully create a `Home` link in the admin panel by doing the following. 

```javascript
  orion.admin.addSidebarTab({
    routeName: 'home',
    navbarTitle: 'Home',
    icon: 'home'
  });
```

**Comment by loongmxbt** [comment]
How to specify the sidebar order for home link? I found the home link in the middle of all links, and I want it to be the top one. Any ideas to do this? Thanks!

**Comment by loongmxbt** [comment]
I think I should customize orionjs:bootstrap to do this.

**Comment by nicolaslopezj** [comment]
This solution is old. In new versions the link is in the top.
https://github.com/orionjs/bootstrap/pull/3

**Comment by loongmxbt** [comment]
That's really cool!
