### ISSUE TITLE
Just built a maps extension for Orionjs

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#46]
I just added a maps extension for Orionjs , users can now call  `orion.attribute('map')`
and add geo code location as a field. 

Used documentation and forked `yogiben:autoform-maps` which extends `aldeed:autoform`

http://screencast.com/t/ZSd85AvdHx 

Repository can be found here. https://github.com/rwatts3/orionjs-maps/

**Comment by nicolaslopezj** [comment]
Good!
