### ISSUE TITLE
Exception in template helper: TypeError: Cannot read property 'objectKeys' of null

### ISSUE THREAD

**Issue by marccantwell** [orionjs/core#47]
http://cl.ly/image/381p443H473x

```
Exception in template helper: TypeError: Cannot read property 'objectKeys' of null
    at Object.autoFormFieldNames (http://localhost:3000/packages/aldeed_autoform.js?238705d312ed82aff928668af1316ae1b2d7ed2a:1383:19)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:16
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:16
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2833:27
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
    at Object.Spacebars.dataMustache (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:141:39)
    at http://localhost:3000/packages/aldeed_autoform.js?238705d312ed82aff928668af1316ae1b2d7ed2a:6292:22
```

**Comment by nicolaslopezj** [comment]
Hi, do you have the latest version of orion?
Do you have the package ```orionjs:bootstrap``` installed?

**Comment by marccantwell** [comment]
I believe so.  Latest version of meteor with a clean install.
http://cl.ly/image/161z0Q3n1I14

```
meteor create APPNAME
meteor add orionjs:bootstrap
```

**Comment by nicolaslopezj** [comment]
With https://github.com/orionjs/core/commit/9a33b6b4f93e41e2d369d2267988ff6e31265f0c the error should disappear. Update the packages.

**Comment by marccantwell** [comment]
This might be related, it might not, but I can't get anything to load properly now with a fresh app and install.  No errors in the console, but not sure where to sniff out what is going on.

http://cl.ly/image/001Z2q3n2Y2p

**Comment by nicolaslopezj** [comment]
You also need to install bootstrap and font awesome.
```meteor add twbs:bootstrap```
```meteor add fortawesome:fontawesome```

**Comment by marccantwell** [comment]
Nice, I have the dependencies working now, but no dictionary, might be related to your earlier commit? http://cl.ly/image/360j3y0p0c1T

**Comment by nicolaslopezj** [comment]
If you don't have any definitions the dictionary tab won't appear (if everything works correctly)
