### ISSUE TITLE
dict usage with html code in value display html

### ISSUE THREAD

**Issue by rdewolff** [orionjs/core#49]
Got a small problam after changed the dict fields am using. Now the field's HTML content, which was initially a textarea, displays the HTML code. It's not rendered.

Is there a way to correct this?

**Comment by rwatts3** [comment]
Try wrapping in triple curly braces {{{' dict 'yourDefinition'}}}

**Comment by rdewolff** [comment]
Thanks @rwatts3 ! That did the trick!

**Comment by rwatts3** [comment]
No problem.
