### ISSUE TITLE
Question : Regarding orion.meteor.com/docs

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#50]
Did you use the pages extension to build orion.meteor.com/docs ?

**Comment by nicolaslopezj** [comment]
No, the site fetchs the readme from github and shows them

**Comment by rwatts3** [comment]
oh ok, if i wanted to use something similar with the pages would that be possible. I guess the question I'm asking is is it possible to build pages or a docs section using the pages extension or is that out of the scope for pages.

**Comment by nicolaslopezj** [comment]
It's totally in the scope. Any doubt you can ask
