### ISSUE TITLE
Best way to load a custom page in the admin panel.  

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#53]
Looked through the API and docs and I may have missed it.  What is the best way to add a custom page to the admin panel.  For instance if I want to add a button called Analytics.  And I want to serve a custom page inside the admin panel that has charts and graphs about the sites analytics.

Maybe even render a custom docs page inside the admin area for new users.

**Comment by nicolaslopezj** [comment]
Here it is
https://github.com/orionjs/core/tree/master/api#adding-tabs

**Comment by rwatts3** [comment]
Will the added tab render the admin layout though ?

**Comment by rwatts3** [comment]
Meaning if I create a template for analytics.  How would I make that template render inside of the admin area instead of just routing to the page itself

**Comment by nicolaslopezj** [comment]
That function only adds the button, you must create the route and specify the layout. Filesystem and pages uses that function, you can use them as example

**Comment by rwatts3** [comment]
Oh good point thanks man.

**Comment by nicolaslopezj** [comment]
Perfect

**Comment by fountainhead** [comment]
@rwatts3 .... I think I need to do something similar. Can you advise how you went about doing this? I haven't explored the code much yet

**Comment by rwatts3** [comment]
Hi.  I haven't done it just yet but have an idea of how I'm going to do it.  I will follow up once I implement my feature.
