### ISSUE TITLE
Question : General Advice

### ISSUE THREAD

**Issue by rwatts3** [orionjs/core#55]
Hi 

I was wonder if you could answer a general question regarding the pull request and branching process.  I've worked on a lot of projects on my own in regards to git but I don't have a lot of experience in terms of collaborating and managing pull requests for a team.  

What I would like to do is fork the orionjs package and make it sync with the original source.  I'm sure I'll need to add an upstream for this.  

However I would also like to create to make a separate branch called features.  Where I can work on new features or features for a special project of my own . I want to ensure that my features branch can inherit the latest updates from the main project without losing my updates as well.  

Essentially the fork will contain a dev branch where I will work on pull requests and issues.  

And a features branch where I will try things out but keep the main updates running in.  

I'm sure this is very ready but I would like your advice before trying to implement.  

For now I have been using aldeeds template extensions package to update various fixes but as you know I am sure the above mentioned approaches are much better .

**Comment by nicolaslopezj** [comment]
I'm sorry, I don't understand you question. I'm not an expert on git, maybe you know more. I you want to make pull request you can make them to the master branch.
I think you can make any branches you want in you fork

**Comment by rwatts3** [comment]
Ok , 

So the base of the question is for the features branch how do I ensure that the branch has the latest code from orionjs but also uses my feature updates ?

**Comment by nicolaslopezj** [comment]
Sorry, I don't know.

**Comment by rwatts3** [comment]
Thank you I think i figured it out.
