### ISSUE TITLE
Q: Users admin?

### ISSUE THREAD

**Issue by mraak** [orionjs/core#61]
I quickly peeked into your example with blog posts, registered there and I didn't see any user management. Ideally I'd like to have the ability to see all users, group them, assign privileges, etc.. Is this possible?

ps: In the blog example app, new blog posts are actually not being saved.

**Comment by nicolaslopezj** [comment]
Of course you can manage users. But you have to be the admin to do that. In the example you are not a admin. 
When you install orion in your app, you can create the admin user. 
Check here http://orion.meteor.com/docs/users

**Comment by mraak** [comment]
Perfect, should've checked the docs first :) Kudos for the great app, looking forward to try it on a project.

**Comment by nicolaslopezj** [comment]
Great! Thanks
