### ISSUE TITLE
Move router for entity CRUD to bootsrap

### ISSUE THREAD

**Issue by timfam** [orionjs/core#65]
Hi Nick,
We should move all routes definition with this pattern ``` /admin/e/:entity/* ``` to bootsrap. I am working on a solution to allow admin to define different template for each entity type. Pull request will be requested shortly. We should have a route.js there

**Comment by nicolaslopezj** [comment]
Awesome!
But can we think an idea to do this without moving iron router?
Maybe using this http://docs.meteor.com/#/full/template_dynamic

**Comment by timfam** [comment]
I am open to suggestions, I tried two different concepts already I was leaning more on just changing the template rendered via the route api. I will pause and give dynamically template a try if that will save us from touching core

**Comment by nicolaslopezj** [comment]
We must touch core. In core we must add the changes to the entity and also helpers for the templates. The important is that we try to not move things

**Comment by timfam** [comment]
Okay. Btw with route api method we don't have to move routes out I just felt since we were touching it we might as well do. Eveything entity should be bootsrap and I doubt any one will be using core without bootstrap? I realize it is a breaking change but this is bleeding edge project, you are practically adding stuff daily and this is just a separation of concerns

**Comment by nicolaslopezj** [comment]
We should try to leave the minimum amount of things in orionjs:bootstrap, because someone could create foundation-views (for example) and the code would be duplicated

**Comment by timfam** [comment]
Your absolutely right about duplication, I didn't see it from the other framework perspective
