### ISSUE TITLE
Newsletter for major releases

### ISSUE THREAD

**Issue by iamkevingreen** [orionjs/core#9]
I know that this is still young, but I think you would benefit from setting up something like a mailchimp for informing users of release updates. I just pulled your latest updates and was confused as to why my admin user was not longer and admin and saw that there is now an admin/setup (I realize theres not a lot of people actively playing with this as much as I am but big changes like this would be nice to know about). I would be interested in contributing to the newsletter releases as well.

**Comment by nicolaslopezj** [comment]
I think that's a excellent idea. I'm going to do it
